language: cpp
sudo: false
dist: bionic

cache:
  directories:
    - $HOME/deps

before_install:
  - curl -o cmake-3.15.3-Linux-x86_64.sh -SL "https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3-Linux-x86_64.sh"
  - chmod +x cmake-3.15.3-Linux-x86_64.sh
  - ./cmake-3.15.3-Linux-x86_64.sh --skip-license --prefix=/usr
  - rm -rf cmake-3.15.3-Linux-x86_64.sh

before_script:
  - bash ./scripts/travis/install_deps.sh $HOME/deps

script:
  - mkdir _build
  - cd _build
  - bash ../scripts/travis/cmake.sh $HOME/deps
  - make publish
  - make
  - ctest

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - cmake
            - ninja-build
            - gcc-9
            - g++-9
      env:
        - BOOST_ROOT="$HOME/deps/boost"
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-4.8
    #   env:
    #      - MATRIX_EVAL="CC=gcc-4.8 CXX=g++-4.8"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-4.9
    #   env:
    #      - MATRIX_EVAL="CC=gcc-4.9 CXX=g++-4.9"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-5
    #   env:
    #      - MATRIX_EVAL="CC=gcc-5 CXX=g++-5"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #   env:
    #     - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-8
    #   env:
    #     - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"


    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-3.8
    #   env:
    #     - MATRIX_EVAL="CC=clang-3.8 CXX=clang++-3.8"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-3.9
    #   env:
    #     - MATRIX_EVAL="CC=clang-3.9 CXX=clang++-3.9"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-4.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-4.0 CXX=clang++-4.0"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-5.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 CXX=clang++-5.0"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-6.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-6.0 CXX=clang++-6.0"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-7
    #   env:
    #     - MATRIX_EVAL="CC=clang-7 CXX=clang++-7"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-8
    #   env:
    #     - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-9
    #   env:
    #     - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

before_install:
  - eval "${MATRIX_EVAL}"
